[tool]
name = "karabiner"
description = "Keyboard customizer"
dependencies = ["brew", "yq", "jq"]

[[link]]
target = "{config_dir}/karabiner"

[scripts]
directory = "scripts"
scripts = ["generate_config.sh"]
